development:
  dialect: postgres
  database: goweb_development
  user: postgres
  password: pgpass
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: goweb_test
  user: postgres
  password: NoSoupForYou
  host: 127.0.0.1
  pool: 5

production:
  url: {{env "DATABASE_URL"}}