[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  version = "0.10.2"

[[constraint]]
  name = "github.com/gobuffalo/envy"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.9.4"

[[constraint]]
  branch = "master"
  name = "github.com/gobuffalo/suite"

[[constraint]]
  branch = "master"
  name = "github.com/markbates/grift"

[[constraint]]
  name = "github.com/markbates/pop"
  version = "3.41.1"

[[constraint]]
  branch = "master"
  name = "github.com/unrolled/secure"
